services:
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file: backend.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  ingestion-layer:
    build: src/ingestion
    env_file: backend.env

  processing-layer:
    build: src/processing
    env_file: backend.env
    depends_on:
      db:
        condition: service_started
        restart: true
    models:
      - llama

models:
  llama:
    model: ai/llama3.2

volumes:
  postgres_data: