services:
  db:
    image: postgres:14-alpine
    restart: always
    env_file:
      - ../backend.env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql